### ISSUE TITLE
安装应用时提示证书过期

### ISSUE THREAD

**Issue by Zim-Inn** [kitUIN/ShadowViewer#31]
### Bug 描述

PowerShell提示如截图所示. 查看证书日期后,发现其最后支持日为2024.0426.
可能需要开发者签发新的证书,发布新assets
![image](https://github.com/kitUIN/ShadowViewer/assets/60260187/41332fba-2643-439d-a699-49acfae8d36e)

### 复现问题的步骤

```plain text
如简述
```

### 日志记录

无

### ShadowViewer应用版本

0.2.2.0 x64

### 电脑系统

win11家庭版

**Comment by kitUIN** [comment]
已经更新文件
