### ISSUE TITLE
[Bug] 插件安装不了

### ISSUE THREAD

**Issue by ioeah** [kitUIN/ShadowViewer#32]
### Bug 描述

不管是添加插件还是将插件解压到插件文件夹，都无法安装

### 复现问题的步骤

```plain text
1. 安装应用
2. 下载插件
3. 添加插件
```

### 日志记录

13:45:34.444 [INFO] ShadowViewer.Helpers.FileHelper | 文件夹C:/Users/34453/AppData/Local/Packages/27e531ce-1721-4ddf-80ef-f4c28f27a46d_ssncz3j6xqbzw/LocalState/Comics不存在,新建 
13:45:34.490 [INFO] ShadowViewer.Helpers.FileHelper | 文件夹C:/Users/34453/AppData/Local/Packages/27e531ce-1721-4ddf-80ef-f4c28f27a46d_ssncz3j6xqbzw/LocalState/Temps不存在,新建 
13:45:34.492 [INFO] ShadowViewer.Helpers.FileHelper | 文件夹C:/Users/34453/AppData/Local/Packages/27e531ce-1721-4ddf-80ef-f4c28f27a46d_ssncz3j6xqbzw/LocalState/Plugins不存在,新建 
13:45:35.588 [INFO] ShadowViewer.Plugin.PluginManager.Services.PluginService | [插件管理器]插件[Local]加载主类成功 
13:45:35.589 [INFO] ShadowViewer.Plugin.PluginManager.Services.PluginService | [插件管理器]插件[Local]加载图片页LocalHistoryResponder注入成功 
13:45:35.589 [INFO] ShadowViewer.Plugin.PluginManager.Services.PluginService | [插件管理器]插件[Local]加载导航LocalNavigationResponder注入成功 
13:45:35.589 [INFO] ShadowViewer.Plugin.PluginManager.Services.PluginService | [插件管理器]插件[Local]加载图片页LocalPicViewResponder注入成功 
13:45:35.593 [INFO] ShadowViewer.Plugin.PluginManager.Services.PluginService | [插件管理器]插件[Local]加载数据库实体类LocalHistory注入成功 
13:45:35.594 [INFO] ShadowViewer.Plugin.PluginManager.Services.PluginService | [插件管理器]插件[Local(本地阅读插件)]加载成功 
13:45:35.825 [INFO] ShadowViewer.Plugin.PluginManager.Services.PluginService | [插件管理器]插件[PluginManager]加载主类成功 
13:45:35.825 [INFO] ShadowViewer.Plugin.PluginManager.Services.PluginService | [插件管理器]插件[PluginManager]加载导航PluginManagerNavigationResponder注入成功 
13:45:35.836 [INFO] ShadowViewer.Plugin.PluginManager.Services.PluginService | [插件管理器]插件[PluginManager(插件管理器)]加载成功 
13:45:35.945 [INFO] ShadowViewer.ViewModels.BookShelfViewModel | 导航到"shadow://local/",Path=local 
13:45:57.569 [INFO] Windows.Storage.Pickers.FileOpenPicker | 选择了文件:D:\download\chrome\ShadowViewer.Plugin.Bika.0.2.1.zip 

### ShadowViewer应用版本

0.2.2

### 电脑系统

win11

**Comment by kitUIN** [comment]
目前还在重构应用 暂时不修bug

**Comment by kitUIN** [comment]
请使用
- ShadowViewer 0.2.9
- ShadowViewer.Plugin.Bika 0.3.0
