### ISSUE TITLE
[Bug] 无法安装插件

### ISSUE THREAD

**Issue by roadchenmin** [kitUIN/ShadowViewer#34]
### Bug 描述

尝试了教程中的两种方法，在插件管理器中点击添加插件，选择下载好的bika插件压缩包，无法安装无异常提示。尝试把解压缩出来的bika文件夹，拖动到应用数据文件夹-插件文件夹中，也无法安装无异常提示。

### 复现问题的步骤

```plain text
1.打开应用 2.点击插件管理 3.点击添加插件 4.选择ShadowViewer.Plugin.Bika-0.2.1.zip. 4.安装后无反应，无异常提示
（使用0.2.0版本的bika插件结果不变）
第二种 1.打开应用 2.点击设置 3.点击应用数据文件夹 4.打开插入文件夹 5.拖入ShadowViewer.Plugin.Bika-0.2.1.zip 6.安装后无反应，无异常提示 （将第五步更改为拖入ShadowViewer.Plugin.Bika-0.2.1结果不变，使用0.2.0版本的bika插件结果不变）
```

### 日志记录

[ShadowViewer20241228.log](https://github.com/user-attachments/files/18262131/ShadowViewer20241228.log)

### ShadowViewer应用版本

V0.2.2.0

### 电脑系统

Win11家庭版24H2

**Comment by kitUIN** [comment]
目前这个版本没法安装插件
预计下周发布下个版本

**Comment by roadchenmin** [comment]
收到，辛苦了，静待佳音，预祝新年快乐

**Comment by kitUIN** [comment]
请使用
- ShadowViewer 0.2.9
- ShadowViewer.Plugin.Bika 0.3.0
